apiVersion: v1
name: lnd
version: 0.15.3
appVersion: 0.14.1
description: A golang implementation of a Lightning Network node
keywords:
  - lnd
  - bitcoin
home: https://github.com/lightningnetwork/lnd
sources:
  - https://github.com/kubernetes/charts
maintainers:
  - name: kiwiidb
    email: kwinten@flitz.be
engine: gotpl
